### ISSUE TITLE
Issue with MicroLib

### ISSUE THREAD

**Issue by hattmt** [STMicroelectronics/STM32CubeG0#18]
**Describe the set-up**
STM32G0 , Keil

**Describe the bug**
CubeMX set MicroLib unchecked at each generation.

**How To Reproduce**
Activate Microlib in Keil (project settings) and regenerate with CubeMX, .
Now go to the project settingds in Keil, it will be unchecked .

![image](https://user-images.githubusercontent.com/56161715/134011285-e9b116be-98e7-4eea-8785-ac92897b922d.png)
![image](https://user-images.githubusercontent.com/56161715/134011478-cf160079-66d1-4059-9f48-1159accc0e9d.png)

**Comment by RKOUSTM** [comment]
Hi  @hattmt,

Thank you for your contribution.

In order to allow a better analysis of this problem, could you please give us more details about the application that you are using to reproduce this issue or did you use one of our applications? 

Also, could you please confirm you are using the latest firmware version and that the issue is systematically reproducible on your side?

Thank you again for your contribution.

With regards,

**Comment by hattmt** [comment]
I use Keil(uVision5) for my project developpment  and STM32CubeMX to generate the HAL initialisation. I am programming on a Stm32G0.
I need MicroLib for my project. So I check the option in Keil to include MicroLib.

Until now, when I generated my project, CubeMX was keeping the Microlib checked in Keil settings at each generation , so it was working : CubeMX wasn't modifiying this setting.

In the new version of STM32CubeMX, each time I generate with CubeMx , it sets my Microlib option  uncheck in Keil. So here CubeMX goes and modify the value in my keil project and set it unchecked , I just need that Stm32CubeMx doesn't modify the settings that are set for microlib like the previous versions.

Regards.

**Comment by RKOUSTM** [comment]
Hi @hattmt,

First we would like to thank you for your contribution.

The issue you pointed out is confirmed. An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference:  114126
