### ISSUE TITLE
I2C Slave examples for STM32G0316-DISCO board

### ISSUE THREAD

**Issue by kholia** [STMicroelectronics/STM32CubeG0#19]
Problem: The STM32G031J6 MCU (on a STM32G0316-DISCO board) is unable to work properly as an I2C Slave when operating in the Interrupt Mode with callbacks functions.

Details:

![Screenshot_2021-09-25_09-35-04](https://user-images.githubusercontent.com/79528/134758248-f56eea12-964f-4f66-a7de-eb56ede3fcc5.png)

![Screenshot_2021-09-25_10-17-19](https://user-images.githubusercontent.com/79528/134758506-a8674ac0-b771-4561-9cda-e8a718ce4340.png)

These screenshots show that the Slave is unable to handle `Data read` requests from the Master I2C device.

The Slave returned data is always `0xFF`. I saw https://www.i2c-bus.org/i2c-primer/analysing-obscure-problems/data-bytes-from-slave-are-0xff/ on this topic.

The I2 Master device is Arduino Pro Mini ATMega328P running @ 8 MHz @ 3.3v.

Note: I am using 2.2k pull-up resistors on the SDA and SCL lines. Removing them doesn't make any difference.

Here is the configured pinout for my STM32G031J6 MCU:

![Screenshot_2021-09-25_09-39-19](https://user-images.githubusercontent.com/79528/134758260-23f13243-8c1f-4adf-947a-a82244998286.png)

I2C2 global interrupt is enabled in my STM32CubeIDE project.

Here is how the I2C pins are configured:

![Screenshot_2021-09-25_09-57-15](https://user-images.githubusercontent.com/79528/134758270-3206d7ef-4899-40f9-9986-74ccb1898625.png)

Clocks are configured as below:

![Screenshot_2021-09-25_10-05-46](https://user-images.githubusercontent.com/79528/134758276-f24ca236-ae13-41ce-9037-23593a90191e.png)

Note: In comparison, when I run a similar STM32CubeIDE project on my STM32F103C8T6  "Blue Pill" board, things just work well as expected (Slave is able to send back actual data).

I am attaching the source code for the I2C Master and I2C Slave (STM32G031J6) below:

- [i2c_slave_code.zip](https://github.com/STMicroelectronics/STM32CubeG0/files/7229160/i2c_slave_code.zip)
- [master.ino.txt](https://github.com/STMicroelectronics/STM32CubeG0/files/7229159/master.ino.txt)

Questions:

- Is I2C Slave Mode (in `Interrupt Mode`) supported on STM32G031J6 MCU?

- Is there a reason why the STM32G0316-DISCO board software package has no `I2C` examples? They will be super helpful for users.

What further information may I provide for debugging this problem? Thanks for your help! :)

**Comment by kholia** [comment]
Possibly related https://community.st.com thread: [Not able to read data from STM32G031 MCU I2C slave](https://community.st.com/s/question/0D53W00000Pnh5A/not-able-to-read-data-from-stm32g031-mcu-i2c-slave).

**Comment by kholia** [comment]
Possibly related issue:

If I enable clock stretching on this STM32G0 MCU, the SCL line goes down, and remains low forever. This could be a bug in my code but very similar code runs perfectly fine on a "Blue Pill" STM32 board with clock stretching enabled.

**Comment by KORKAD** [comment]
Hello @kholia,
Please note that similaire HAL I2C examples are already available for STM32G031K8 MCU but on Nucleo board not the DISCO.

For more details please refer to the I2C_TwoBoards_RestartComIT example. 

With Regards
KORKAD

**Comment by kholia** [comment]
Thanks! This ticket may be closed.
