### ISSUE TITLE
Missing UNUSED macro

### ISSUE THREAD

**Issue by SHWarema** [STMicroelectronics/STM32CubeG0#20]
In the following functions one usage of `UNUSED()` macro is missing respectively:
- stm32g0xx_ll_adc.c
  - `ErrorStatus LL_ADC_CommonDeInit(ADC_Common_TypeDef *ADCxy_COMMON)`
    - `ADCxy_COMMON`
- stm32g0xx_hal_rtc_ex.c
  - `HAL_StatusTypeDef HAL_RTCEx_SetTimeStamp(RTC_HandleTypeDef *hrtc, uint32_t TimeStampEdge, uint32_t RTC_TimeStampPin)`
    - `RTC_TimeStampPin`
  - `HAL_StatusTypeDef HAL_RTCEx_SetTimeStamp_IT(RTC_HandleTypeDef *hrtc, uint32_t TimeStampEdge, uint32_t RTC_TimeStampPin)`
    - `RTC_TimeStampPin`
- stm32g0xx_hal_cortex.c
  - `void HAL_NVIC_SetPriority(IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)`
    - `SubPriority`

**Comment by RKOUSTM** [comment]
Hi @SHWarema,

I hope you are fine. The issue you reported has been fixed in the frame of version v1.5.1 of the STM32CubeG0 published recently on GitHub.

Thank you again for having reported.

With regards,
