### ISSUE TITLE
Strange casts in stm32g0xx_ll_usart.h

### ISSUE THREAD

**Issue by SHWarema** [STMicroelectronics/STM32CubeG0#21]
In stm32g0xx_ll_usart.h there are three inline functions using the `MODIFY_REG()` macro that are generating the following warnings when compiled with ARM Compiler 6 (Clang/LLVM):
![image](https://user-images.githubusercontent.com/92387863/137089749-2790254a-0383-486f-8274-4d0aa948e375.png)

I think all of the casts to `uint16_t` in the following functions should be removed:
- `__STATIC_INLINE void LL_USART_SetIrdaPrescaler(USART_TypeDef *USARTx, uint32_t PrescalerValue)`
- `__STATIC_INLINE void LL_USART_SetSmartcardPrescaler(USART_TypeDef *USARTx, uint32_t PrescalerValue)`
- `__STATIC_INLINE void LL_USART_SetSmartcardGuardTime(USART_TypeDef *USARTx, uint32_t GuardTime)`

**Comment by ASELSTM** [comment]
Hi @SHWarema,

Thank you for your contribution. This issue has been fixed in the frame of version v1.5.1 of the STM32CubeWB. Please allow me then to close this thread.

Thank you again for your contribution.

With regards,
