### ISSUE TITLE
UART PRINTF example is not working on IAR 9.2

### ISSUE THREAD

**Issue by jealcuna** [STMicroelectronics/STM32CubeG0#26]
Tested in stm32g070 using UART3.

Write my own implementation of fputc function, add stdio.h in main.h header. Also add _DLIB_FILE_DESCRIPTOR in preprocessor.
Breakpoint does not reach fputc.

**Comment by ASELSTM** [comment]
Hi @jealcuna,

We do  not support yet the **EWARM V9.2** within our STM32CubeG0 Firmware package. As mentioned in the Firmware project [ Release Note](https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeG0/blob/master/Projects/Release_Notes.html), the latest EWARM version supported is **V8.50.6**.

Please allow me thus to close this thread. Thank you for you comprehension and for contribution.

With regards,
