### ISSUE TITLE
STM32 RTC loses one second after each reset

### ISSUE THREAD

**Issue by Adityasingh8394** [STMicroelectronics/STM32CubeG0#30]
This issue is not yet resolved for G0 series

https://community.st.com/s/question/0D50X00009XkgBWSAZ/stm32-rtc-loses-one-second-after-each-reset

**Comment by ALABSTM** [comment]
Hi @Adityasingh8394,

Thank you for this report. We will get back to you with a feedback as soon as possible. Please excuse the delay it may take us sometimes to reply. Thank you for your comprehension.

With regards,

**Comment by ALABSTM** [comment]
Same as [STM32CubeWL#29](https://github.com/STMicroelectronics/STM32CubeWL/issues/29).

**Comment by ALABSTM** [comment]
Related to [STM32CubeH7#24](https://github.com/STMicroelectronics/STM32CubeH7/issues/24)

**Comment by ALABSTM** [comment]
ST Internal Reference: 126469

**Comment by ALABSTM** [comment]
Hi @Adityasingh8394 and @IngmarPaetzold,

Hope you're doing well. Just to let you know this issue has been fixed in the frame of version **1.6.0**.

With regards,
