### ISSUE TITLE
Missing #if defined in LL RCC header file

### ISSUE THREAD

**Issue by badcf00d** [STMicroelectronics/STM32CubeG0#45]
STM32G061 Does not define `RCC_CCIPR_USART2SEL`, however there is no `#if defined(RCC_CCIPR_USART2SEL)` like there is for `USART3`

https://github.com/STMicroelectronics/STM32CubeG0/blob/ae31d181b3244190d7d5bc0d91e66a82ce4270ce/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_ll_rcc.h#L376-L386

Please could this be fixed?

**Comment by TOUNSTM** [comment]
ST Internal Reference: 165399

**Comment by TOUNSTM** [comment]
Fixed in this commit 44648d8e4476021838a694fad1c211254d59fcca
